name: Ejecutar pruebas de CodeceptJS

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas de CodeceptJS
        run: npx codeceptjs run --steps | tee output.log

      - name: Subir log como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: reporte-codeceptjs
          path: output.log