name: Ejecutar pruebas de CodeceptJS

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Verificar versiones
        run: node -v && npm -v

      - name: Instalar dependencias del proyecto
        run: npm ci

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Instalar Allure CLI (v2)
        run: npm install -g allure-commandline@2.20.1

      - name: Ejecutar pruebas de CodeceptJS
        run: npx codeceptjs run --steps

      - name: Generar reporte de Allure
        if: always()
        run: |
          allure generate output --clean -o allure-report
          ls allure-report

      - name: Verificar existencia del reporte de Allure
        if: always()
        run: |
          if [ ! -d "allure-report" ]; then
            echo "No se generó el directorio allure-report"
            exit 1
          fi

      - name: Subir reporte de Allure como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-allure
          path: allure-report